---
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: "istio-servicea"
  labels:
    app: service-a
spec:
  ports:
    - port: 8091
      name: http
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: "istio-servicea"
  labels:
    app: service-a
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
        version: v1
    spec:
      containers:
        - name: app
          image: abisruthi/microservices:seviceA1
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
