---
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
  namespace: "istio-serviced"
  labels:
    app: service-d
spec:
  ports:
    - port: 8094
      name: http
  selector:
    app: service-d
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: "istio-serviced"
  labels:
    app: service-d
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
        version: v1
    spec:
      containers:
        - name: app
          image: abisruthi/microservices:seviceD1
          env:
             - name: SERVICE_HOST
               value: service-a.istio-servicea.svc.cluster.local
             - name: SERVICE_PORT
               value: "8091"
          imagePullPolicy: Always
          ports:
            - containerPort: 8094

