---
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: "servicec"
  labels:
    app: service-c
spec:
  ports:
    - port: 8093
      name: http
  selector:
    app: service-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: "servicec"
  labels:
    app: service-c
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
        version: v1
    spec:
      containers:
        - name: app
          image: abisruthi/microservices:seviceC1
          env:
             - name: SERVICE_HOST
               value: service-a.istio-servicea.svc.cluster.local
             - name: SERVICE_PORT
               value: "8091"
          imagePullPolicy: Always
          ports:
            - containerPort: 8093
