---
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: "istio-serviceb"
  labels:
    app: service-b
spec:
  ports:
    - port: 8092
      name: http
  selector:
    app: service-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: "istio-serviceb"
  labels:
    app: service-b
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        version: v1
    spec:
      serviceAccountName: auth-test-sa      
      containers:
        - name: app
          image: abisruthi/microservices:seviceB1
          env:
            - name: SERVICE_HOST
              value: service-a.istio-servicea.svc.cluster.local
            - name: SERVICE_PORT
              value: "8091"
          imagePullPolicy: Always
          ports:
            - containerPort: 8092

